### ISSUE TITLE
WooCommerce Integration

### ISSUE THREAD

**Issue by Annalyn** [suomato/base-camp#12]
Hi Toni,

I would like to thank you for building base-camp.  I enjoy using this for my projects.  Is there any chance you can add WooCommerce integration for this?  I followed Timber's woocomerce guide, but I guess it only works in their repo.

Thanks again,
Annalyn

**Comment by Annalyn** [comment]
Hello, again Toni!

Here I go again.  I remember the first time I submitted an issue and I fixed it right away.  Please disregard this issue as I made the WooCommerce integration work :) Thanks again :)

- Annalyn

**Comment by suomato** [comment]
Hello @Annalyn 

Good to hear that you figured it out. As far as I know WooCommerce is the most popular eCommerce platform used in WordPress so I should definitely add WooCommerce integration for Base Camp. :)

**Comment by Annalyn** [comment]
That would be perfect @suomato.  Looking forward to the integration! Have a nice weekend!
