### ISSUE TITLE
 'Dotenv\Dotenv' not found

### ISSUE THREAD

**Issue by thepedroferrari** [suomato/base-camp#13]
Hi there,

I am excited to try out your theme as it seems really promising, but as soon as I enable the theme I am getting this error:

> 
> Fatal error: Uncaught Error: Class 'Dotenv\Dotenv' not found in C:\xampp\htdocs\conversionista\wp-content\themes\base-camp\app\bootstrap.php:7 Stack trace: #0 C:\xampp\htdocs\base-camp\wp-content\themes\base-camp\functions.php(4): require_once() #1 C:\xampp\htdocs\base-camp\wp-settings.php(426): include('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\base-camp\wp-config.php(89): require_once('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\base-camp\wp-load.php(37): require_once('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\base-camp\wp-admin\admin.php(31): require_once('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\base-camp\wp-admin\themes.php(10): require_once('C:\\xampp\\htdocs...') #6 {main} thrown in C:\xampp\htdocs\base-camp\wp-content\themes\base-camp\app\bootstrap.php on line 7

These are the original files, I tried re-installing, downloading again a few times. I also checked the files and the class is being called right after autoload.

I am trying this on Windows 10 / xampp php 7.1 and also Trellis/Bedrock/vagrant latest version. I have all dependencies installed as well :)

Thank you a lot!

**Comment by thepedroferrari** [comment]
Sorry, the problem wasn't with the theme, I just fixed it and it worked with the new composer version. 1.6 / 1.6.1 were buggy, the 1.6.2 addressed the issue

Take care and thanks! I'm going to start digging up on your theme now ;)

**Comment by suomato** [comment]
Hi,

I hope you will find it useful!
