### ISSUE TITLE
Refresh css styles without page reload

### ISSUE THREAD

**Issue by webwaldo** [suomato/base-camp#16]
Hey, 

Loving the base-camp starter theme, have used parts of the stack before, but not all at once, so its nice to have it all combined. 

Do you know any way to configure webpack/browsersync so that css styles will inject without a page refresh? 

From what I understand, browsersync should just inject the new css, but because the js gets rebuilt, even on just a css change, the new js file triggers the reload.

Cheers

**Comment by suomato** [comment]
Hi,

base-camp uses `browser-sync-webpack-plugin` and it seems that there is an option `injectCss` which should work as you wanted. However, I couldn't get it work and according to [this issue](https://github.com/Va1/browser-sync-webpack-plugin/issues/69) there might be a problem with `webpack 4` or `mini-css-extract-plugin`.

**Comment by michelmany** [comment]
Hi. Has this issue been fixed?

**Comment by suomato** [comment]
Hi. Unfortunately no it doesn't. I haven't figured out solution yet.

**Comment by suomato** [comment]
@webwaldo @michelmany this is finally fixed. Now CSS is injected without page reload as long as the sass changes doesn't affect on JavaScript.

**Comment by michelmany** [comment]
Thanks a lot @suomato
