### ISSUE TITLE
Purge CSS and WordPress Generated Classes

### ISSUE THREAD

**Issue by jrjbooth** [suomato/base-camp#18]
Hi, sorry if this is'nt the right place, i'm having an issues where by including wp generated classes into the sass files are removed by purge css. It also appears that purge css is set to run on the complied 'app.css' file within resources so their is no clear way to whitelist these classes. Is this the case or have I misunderstood how purge is working and is there a workaround for it?

Thanks

**Comment by suomato** [comment]
Hi,

Unfortunately purgeCSS can't see generated wp classes and it will delete all styles from app.css related to generated classes. One option is create separated .sass file for example `/resources/assets/sass/wp.sass` and put all styles there which you don't want to purged 

If you do that, remember to add webpack config
```
module.exports = {
  entry: {
    ...
    wp: glob.sync('./resources/assets/+(s[ac]ss|js)/wp.+(s[ac]ss|js)'),
    ...
```
You can also whitelist all wp classes to purgeCSS config but it will be pain in the ass. In my opinion it is not a big deal to give up completely from purgeCSS.

**Comment by jrjbooth** [comment]
Thanks for the pointer, I've ended up whitelisting the wp generated classes in the webpack.conf.
`whitelist: ['screen-reader-text', 'wp-caption', 'wp-caption-text', 'aligncenter', 'alignright', 'alignleft', 'alignnone'],` 
And adding _wp.sass into the sass folder, to me it looks like the best solution.
If I could star this repo twice, I would, love what your doing!
