### ISSUE TITLE
Security Function creates double pageload in admin area

### ISSUE THREAD

**Issue by gillesgoetsch** [suomato/base-camp#19]
Hey there. Using your boiler base quite intensively for a while now.
I'll maybe create a fork with all the tweaks I did to it.

One thing that I think is important for this repo:
The Line in config/wp/security.php creates a double pageload in the admin-area. It happens, that the page first loads, and then loads again. I just recognised this cause I was doing performance-optimizations.

`add_filter('style_loader_src', 'base_camp_remove_query_string_version', 9999);`

<img width="1277" alt="screenshot 2018-10-17 at 16 12 56" src="https://user-images.githubusercontent.com/2161918/47092656-c70ee600-d227-11e8-804a-fc93cd0116fb.png">

**Comment by suomato** [comment]
Hello there!

I didn't even notice that. What do you suggest? Should I remove that filter entirely or should that filter be executed only on frontend side?

**Comment by gillesgoetsch** [comment]
Hey there.
You could wrap it like: `if ( ! is_admin() ) {`
But haven't tested this yet.

**Comment by suomato** [comment]
@gillesgoetsch now it is fixed!
