### ISSUE TITLE
Error when deploying the site remotely

### ISSUE THREAD

**Issue by Annalyn** [suomato/base-camp#6]
HI there,  It is my first to to use base-camp for my development and I am currently uploaded the site for review but I get this error:

Warning: require(/var/www/html/wp-content/themes/jennifer/vendor/composer/../../app/helpers.php): failed to open stream: No such file or directory in /var/www/html/wp-content/themes/jennifer/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/html/wp-content/themes/jennifer/vendor/composer/../../app/helpers.php' (include_path='.:/usr/share/php') in /var/www/html/wp-content/themes/jennifer/vendor/composer/autoload_real.php on line 66

Thanks in advance!

**Comment by Annalyn** [comment]
I remember I disabled autoload. I am not sure if that's the reason why I get this issue.

**Comment by suomato** [comment]
Hello there @Annalyn . What do you mean that you have disabled autoload? Have you tried to delete `vendor` folder and then run `composer install`?

**Comment by Annalyn** [comment]
Hi Suomato,

It is all fixed now.  I destroyed my droplet and created a new one.  I used Duplicator plugin on my first droplet and it wasn't working the way It supposed to so I did the old way of migrating the site from local to remote, manually it is lol! And it works perfectly.

Thank you for your reply and thank you for creating this awesome starter theme.  I am going to close this issue now.
