### ISSUE TITLE
Parse error: syntax error, unexpected '?' in (...)/vendor/suomato/luna/src/helpers.php on line 8

### ISSUE THREAD

**Issue by jvmonjo** [suomato/base-camp#7]
I get this error in php 5.6 envioronment:

`Parse error: syntax error, unexpected '?' in (...)/vendor/suomato/luna/src/helpers.php on line 8`

In PHP 7.0 and 7.1 works fine

**Comment by suomato** [comment]
Hi @jvmonjo. According to theme requirements you should use at least PHP 7.0.

**Comment by jvmonjo** [comment]
I was just wondering, from my ignorance, if that was the only issue in PHP 5.6 and if it was easy to fix, you could support php 5.6 so you can get to more people.

But I guess there will be more problems if you chosen not to support php 5.6 so feel free to clese the issue.

**Comment by suomato** [comment]
I think that it is only issue in PHP 5.6 and I can fix that. I still strongly recommend using PHP 7.0 or PHP 7.1
