### ISSUE TITLE
Vuejs running in development mode after deploy

### ISSUE THREAD

**Issue by jvmonjo** [suomato/base-camp#8]
After running `yarn prod` you would expect Vuejs to minimize and delete comments and logs.

What we are currently seeing is a log warning as that we are running Vue in development mode

**Comment by suomato** [comment]
I pushed [fixed webpack config](https://github.com/suomato/base-camp/commit/36021c632e02482ae0ee5a7214be859c786606bf) to develop branch. Did that help?

**Comment by suomato** [comment]
Actually I made new [release](https://github.com/suomato/base-camp/tree/v1.4.2) with updated Webpack config. Now Vuejs should work in the production mode.

**Comment by jvmonjo** [comment]
Thank you so much ;)
